name: Github actions

on: workflow_dispatch

env:
  APP_ENV: "dev"

jobs:
  env_demo:
    runs-on: ubuntu-latest
    env:
      APP_ENV: "Prod"

    steps:
      - name: connect
        env:
          APP_ENV: "stage"
        run: echo "env is $APP_ENV"

