name: secret
on: 
  push:
    branches:
      - main
      - dev
      - prod
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: scret
        run: echo "this is my ${{ secrets.DOCKER_PASSWD }}"  
